name: Deploy Node Application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker Image
        run: docker build -t amudhavallir/stay-hub-backend .
      - name: Publish Image to Docker Hub
        run: docker push amudhavallir/stay-hub-backend:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from Docker Hub
        run: docker pull amudhavallir/stay-hub-backend:latest
      - name: Delete old Container
        run: docker rm -f stay-hub-backend
      - name: Run Docker Container
        run: docker run -d -p 7000:7000 --name stay-hub-backend -e MONGODB_CONNECTION_STRING="${{ secrets.MONGODB_CONNECTION_STRING }}" -e JWT_SECRET_KEY="${{ secrets.JWT_SECRET_KEY }}" -e FRONTEND_URL="${{ secrets.FRONTEND_URL }}" -e CLOUDINARY_CLOUD_NAME="${{ secrets.CLOUDINARY_CLOUD_NAME }}" -e CLOUDINARY_API_KEY="${{ secrets.CLOUDINARY_API_KEY }}" -e CLOUDINARY_API_SECRET="${{ secrets.CLOUDINARY_API_SECRET }}" -e STRIPE_API_KEY="${{ secrets.STRIPE_API_KEY }}" amudhavallir/stay-hub-backend
